### ISSUE TITLE
Not working on CX

### ISSUE THREAD

**Issue by marce14-git** [andrewfraley/magic_mapper#10]
When starting the script on a CX TV the log post the following errors:

```
Traceback (most recent call last):
  File "/home/root/magic_mapper.py", line 479, in <module>
    main()
  File "/home/root/magic_mapper.py", line 472, in main
    button_map = get_button_map()
  File "/home/root/magic_mapper.py", line 288, in get_button_map
    button_map = json.load(config_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

On my other C1 TV its working flawelessly
thx in advance

**Comment by marce14-git** [comment]
it was a config error on my side... forgot a ","
