### ISSUE TITLE
cannot get it to function. Webos 8.2

### ISSUE THREAD

**Issue by Sogree2** [andrewfraley/magic_mapper#12]
Hello Andrew

I am trying to remap buttons on my new magic remote from my LG G3. It runs Webos 8.2.0.710. I followed the root and install instructions to the letter. My device is successfully rooted. I wget all the files and they reside in the correct location. Also the chmod did not give an error message. (so I believe Magic Mapper is running). For testing I only left the eye comfort and energy mode options in the JSON....... but regrettably the remapping does not work. This is in my JSON:

{
  "yellow": {
    "function": "cycle_energy_mode",
    "inputs": {
      "reverse_order": false,
      "notifications": true
    }
  },
  "blue": {
    "function": "toggle_eye_comfort",
    "inputs": {
      "notifications": true
    }
   }
}

I rebooted the tv through the homebrew cogwheel. Do I need to do extra steps or how can i check that Magic Mapper is correctly running? (I cannot find the logfile).

**Comment by andrewfraley** [comment]
Hi @Sogree2 , apologies for the late reply.   If you're not seeing a log file, either the startup script isn't being executed, or it's erroring out before even running.  SSH into the TV and run the following to see if the script is running:

```
ps aux | grep magic
```

If you see something like this, magic mapper is running.  (It doesn't sound like it is for you, though)

```
root      5417  0.0  0.1   9116  4392 ?        S    12:19   0:00 /usr/bin/python -u /home/root/magic_mapper.py
```

If it is in fact running, kill it.  The process id is the number after "root", so to kill it:

```
kill -9 5417
```

Once killed you can run `ps aux | grep magic` again to confirm it's killed.

Now try to run magic mapper manually to hopefully see the error:

LG C9/CX or older:
```
cd /home/root
python magic_mapper.py
```

LG C1/C2/C3 or newer:
```
cd /home/root
python3 magic_mapper.py
```

**Comment by Oleg-Air** [comment]
I have absolutely the same situation on my C2. TVis rooted and skript is successfully installed and running. But no actions are happening. Have not touched the default JSON settings.

![image](https://github.com/andrewfraley/magic_mapper/assets/112019472/ef4b2c64-d69a-4a36-8429-e499d0129b1b)

**Comment by Oleg-Air** [comment]
Managed to find this error.

root@LGwebOSTV:~# python3 magic_mapper.py
^CTraceback (most recent call last):
  File "magic_mapper.py", line 479, in <module>
    main()
  File "magic_mapper.py", line 475, in main
    input_loop(button_map=button_map)
  File "magic_mapper.py", line 433, in input_loop
    event = input_device.read(event_size)
KeyboardInterrupt

**Comment by andrewfraley** [comment]
@Oleg-Air do you see anything in /tmp/magic_mapper.log ?

**Comment by andrewfraley** [comment]
@Oleg-Air also when you tried to kill the process, you used the pid from my example, but your pid in this case was 6628, so killing the script failed.

**Comment by Oleg-Air** [comment]
Yes, I noticed that and tried the correct one. Killing the skript works fine. But somehow it stuck when I try to run it manually then. 
It hangs so for 30 minutes now.
![image](https://github.com/andrewfraley/magic_mapper/assets/112019472/78f05f57-07d2-479d-9747-c5a716c616a2)

**Comment by Oleg-Air** [comment]
> @Oleg-Air do you see anything in /tmp/magic_mapper.log ?

![image](https://github.com/andrewfraley/magic_mapper/assets/112019472/40143b73-baa0-4102-9288-521bd3b2388f)

**Comment by andrewfraley** [comment]
@Oleg-Air thanks, do you know what WebOS version you're running?  Also could you give me the output of the following, please? 

`uname -a`

If you're on a newer version of WebOS than I am, it's possible they've changed something that's breaking this.  Lastly, make sure the script isn't still running in the background when you're running it manually.  I would expect to see that error if the script was already running.

**Comment by Oleg-Air** [comment]
Hello, 

I do have WebOS23
Software 13.30.56

root@LGwebOSTV:~# uname -a
Linux LGwebOSTV 5.4.96-307 #1 SMP PREEMPT Tue Apr 9 20:57:38 UTC 2024 aarch64 GNU/Linux

I have not tested your Skript before unfortunately but had such high hopes that it could help me to control the Volume of the ARC-connected HDMI Yamaha receiver. Which is a HUGE pain in the back now, cause I need to do it via TVs menu.

**Comment by PeeBeerBeach** [comment]
I think the script runs fine but doesnt recognize any button presses. This might be due to using a wrong input device. At least that solved it for me. Try to this or any different device number:

`INPUT_DEVICE = "/dev/input/event2"`

You have to change this in the python script and then rerun the script.

**Comment by andrewfraley** [comment]
If anyone is having the same issue, could you please supply the output of: 

`cat /proc/bus/input/devices`

@PeeBeerBeach if you could provide yours as well that'd be greatly appreciated.  Thanks!

**Comment by rdzviper** [comment]
LG C2 13.30.56
switch to event2 works for me
_INPUT_DEVICE = "/dev/input/event2"_ 

```
I: Bus=0006 Vendor=0001 Product=0001 Version=0004
N: Name="CHECK INPUT"
P: Phys=
S: Sysfs=/devices/virtual/input/input0
U: Uniq=
H: Handlers=kbd event0 
B: PROP=0
B: EV=3
B: KEY=ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

I: Bus=0003 Vendor=0001 Product=0001 Version=0004
N: Name="LGE RCU"
P: Phys=
S: Sysfs=/devices/virtual/input/input1
U: Uniq=
H: Handlers=kbd event1 
B: PROP=0
B: EV=7
B: KEY=ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe
B: REL=0

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [0]"
P: Phys=
S: Sysfs=/devices/virtual/input/input2
U: Uniq=
H: Handlers=kbd js0 event2 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [1]"
P: Phys=
S: Sysfs=/devices/virtual/input/input3
U: Uniq=
H: Handlers=kbd js1 event3 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [2]"
P: Phys=
S: Sysfs=/devices/virtual/input/input4
U: Uniq=
H: Handlers=kbd js2 event4 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE TONE+ - Builtin [3]"
P: Phys=
S: Sysfs=/devices/virtual/input/input5
U: Uniq=
H: Handlers=kbd js3 event5 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE Simple Premium"
P: Phys=
S: Sysfs=/devices/virtual/input/input6
U: Uniq=
H: Handlers=kbd js4 event6 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="Bluetooth-audio-source"
P: Phys=
S: Sysfs=/devices/virtual/input/input7
U: Uniq=
H: Handlers=kbd event7 
B: PROP=0
B: EV=3
B: KEY=3fffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

I: Bus=0003 Vendor=0001 Product=0001 Version=0001
N: Name="IoT keypad"
P: Phys=
S: Sysfs=/devices/virtual/input/input8
U: Uniq=
H: Handlers=kbd event8 
B: PROP=0
B: EV=3
B: KEY=7fffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe


```

**Comment by PeeBeerBeach** [comment]
Sorry for the delay. I just got aware of your request for support tonight.
Here you go:

`~ # cat /proc/bus/input/devices
I: Bus=0006 Vendor=0001 Product=0001 Version=0004
N: Name="CHECK INPUT"
P: Phys=
S: Sysfs=/devices/virtual/input/input0
U: Uniq=
H: Handlers=kbd event0
B: PROP=0
B: EV=3
B: KEY=ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

I: Bus=0003 Vendor=0001 Product=0001 Version=0004
N: Name="LGE RCU"
P: Phys=
S: Sysfs=/devices/virtual/input/input1
U: Uniq=
H: Handlers=kbd event1
B: PROP=0
B: EV=7
B: KEY=ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe
B: REL=0

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [0]"
P: Phys=
S: Sysfs=/devices/virtual/input/input2
U: Uniq=
H: Handlers=kbd js0 event2
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [1]"
P: Phys=
S: Sysfs=/devices/virtual/input/input3
U: Uniq=
H: Handlers=kbd js1 event3
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [2]"
P: Phys=
S: Sysfs=/devices/virtual/input/input4
U: Uniq=
H: Handlers=kbd js2 event4
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE TONE+ - Builtin [3]"
P: Phys=
S: Sysfs=/devices/virtual/input/input5
U: Uniq=
H: Handlers=kbd js3 event5
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE Simple Premium"
P: Phys=
S: Sysfs=/devices/virtual/input/input6
U: Uniq=
H: Handlers=kbd js4 event6
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="Bluetooth-audio-source"
P: Phys=
S: Sysfs=/devices/virtual/input/input7
U: Uniq=
H: Handlers=kbd event7
B: PROP=0
B: EV=3
B: KEY=3fffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

I: Bus=0003 Vendor=0001 Product=0001 Version=0001
N: Name="IoT keypad"
P: Phys=
S: Sysfs=/devices/virtual/input/input8
U: Uniq=
H: Handlers=kbd event8
B: PROP=0
B: EV=3
B: KEY=7fffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe
`

**Comment by PeeBeerBeach** [comment]
```python
~ # cat /proc/bus/input/devices
I: Bus=0006 Vendor=0001 Product=0001 Version=0004
N: Name="CHECK INPUT"
P: Phys=
S: Sysfs=/devices/virtual/input/input0
U: Uniq=
H: Handlers=kbd event0
B: PROP=0
B: EV=3
B: KEY=ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

I: Bus=0003 Vendor=0001 Product=0001 Version=0004
N: Name="LGE RCU"
P: Phys=
S: Sysfs=/devices/virtual/input/input1
U: Uniq=
H: Handlers=kbd event1
B: PROP=0
B: EV=7
B: KEY=ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe
B: REL=0

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [0]"
P: Phys=
S: Sysfs=/devices/virtual/input/input2
U: Uniq=
H: Handlers=kbd js0 event2
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [1]"
P: Phys=
S: Sysfs=/devices/virtual/input/input3
U: Uniq=
H: Handlers=kbd js1 event3
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [2]"
P: Phys=
S: Sysfs=/devices/virtual/input/input4
U: Uniq=
H: Handlers=kbd js2 event4
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE TONE+ - Builtin [3]"
P: Phys=
S: Sysfs=/devices/virtual/input/input5
U: Uniq=
H: Handlers=kbd js3 event5
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE Simple Premium"
P: Phys=
S: Sysfs=/devices/virtual/input/input6
U: Uniq=
H: Handlers=kbd js4 event6
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 0 65f83fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="Bluetooth-audio-source"
P: Phys=
S: Sysfs=/devices/virtual/input/input7
U: Uniq=
H: Handlers=kbd event7
B: PROP=0
B: EV=3
B: KEY=3fffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

I: Bus=0003 Vendor=0001 Product=0001 Version=0001
N: Name="IoT keypad"
P: Phys=
S: Sysfs=/devices/virtual/input/input8
U: Uniq=
H: Handlers=kbd event8
B: PROP=0
B: EV=3
B: KEY=7fffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

```

**Comment by Oleg-Air** [comment]
Hello, I changed 

OTPUT_DEVICE = "/dev/input/event5" and it started to work. Am so super happy. The only think I am missing now is long press for volume for the external device.

**Comment by Sogree2** [comment]
Sorry for the late reply. I started the post. For me it started working (without calling a different device). I do not know what I did to make it work.

**Comment by mattokar** [comment]
In my case it was caused by forgotten USB dongle from logitech keyboard

**Comment by thewildtree** [comment]
Can confirm changing to `/dev/input/event2` helped on a C3 running webOS 9.2.0. Here's `/proc/bus/input/devices` in case it's still useful:

```
I: Bus=0003 Vendor=0001 Product=0001 Version=0004
N: Name="LGE RCU"
P: Phys=
S: Sysfs=/devices/virtual/input/input0
U: Uniq=
H: Handlers=kbd event0 
B: PROP=0
B: EV=7
B: KEY=ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe
B: REL=0

I: Bus=0006 Vendor=0001 Product=0001 Version=0004
N: Name="CHECK INPUT"
P: Phys=
S: Sysfs=/devices/virtual/input/input1
U: Uniq=
H: Handlers=kbd event1 
B: PROP=0
B: EV=3
B: KEY=ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [0]"
P: Phys=
S: Sysfs=/devices/virtual/input/input2
U: Uniq=
H: Handlers=kbd js0 event2 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 f 65f87fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [1]"
P: Phys=
S: Sysfs=/devices/virtual/input/input3
U: Uniq=
H: Handlers=kbd js1 event3 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 f 65f87fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE M-RCU - Builtin [2]"
P: Phys=
S: Sysfs=/devices/virtual/input/input4
U: Uniq=
H: Handlers=kbd js2 event4 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 f 65f87fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE TONE+ - Builtin [3]"
P: Phys=
S: Sysfs=/devices/virtual/input/input5
U: Uniq=
H: Handlers=kbd js3 event5 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 f 65f87fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="LGE Simple Premium"
P: Phys=
S: Sysfs=/devices/virtual/input/input6
U: Uniq=
H: Handlers=kbd js4 event6 
B: PROP=0
B: EV=f
B: KEY=7f0350 fc00 0 f 65f87fbf cdffffff 80bee01e f0030004 88000000 40 0 7fffff ffffffff 20206003 e9081e28 0 0 0 0 0 0 0 0 0 0 1000 100fc000 2001440 0 0 70000 20000 2018000 4180 10801 9e1680 0 0 10000ffc
B: REL=100
B: ABS=3

I: Bus=0003 Vendor=0000 Product=0000 Version=0004
N: Name="Bluetooth-audio-source"
P: Phys=
S: Sysfs=/devices/virtual/input/input7
U: Uniq=
H: Handlers=kbd event7 
B: PROP=0
B: EV=3
B: KEY=3fffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe

I: Bus=0003 Vendor=0000 Product=0000 Version=0001
N: Name="ClickableMouse"
P: Phys=
S: Sysfs=/devices/virtual/input/input8
U: Uniq=
H: Handlers=js5 event8 
B: PROP=0
B: EV=f
B: KEY=70000 0 0 0 0 0 0 0 0
B: REL=3
B: ABS=3

I: Bus=0003 Vendor=0001 Product=0001 Version=0001
N: Name="IoT keypad"
P: Phys=
S: Sysfs=/devices/virtual/input/input9
U: Uniq=
H: Handlers=kbd event9 
B: PROP=0
B: EV=3
B: KEY=7fffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff fffffffe
```

**Comment by andrewfraley** [comment]
If anyone is still having issues with this and you want to try again, try the latest version of the script.  It seems for 2s at startup now which seems to fix some issues I was having on first boot.  The logging is also greatly improved which may provide more insight into where it's getting hung up if it still won't start correctly.
