### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by Majkysek** [andrewfraley/magic_mapper#17]
hi, I used magic mapper for about half a year, everything worked perfectly, but yesterday I installed a new application https://github.com/aabytt/custom-screensaver-aerial and since then magic mapper is not working i uninstalled the app and reinstalled magic mapper and it still doesn't work. I tried to kill the script and turn it on again manually, the script runs but the controller does not respond. I'm desperate, can someone help me? 
log `Traceback (most recent call last):
  File "/home/root/magic_mapper.py", line 480, in <module>
    main()
  File "/home/root/magic_mapper.py", line 476, in main
    input_loop(button_map=button_map)
  File "/home/root/magic_mapper.py", line 430, in input_loop
    fcntl.ioctl(input_device, EVIOCGRAB, 1)
IOError: [Errno 16] Device or resource busy
`

**Comment by Majkysek** [comment]
After reading the issues here i edited to
INPUT_DEVICE = "/dev/input/event5"
now it works but 4 buttons are broken namely:
```
    139: "settings",
    241: "sources",
    773: "home",
    412: "back",
```
I tried adding them to magic_mapper.py
and I edited the magic_mapper_config.json file
thus:
`  "home": {
    "function": "press_button",
    "inputs": {
      "button": "home"
    }
  },
  "back": {
    "function": "press_button",
    "inputs": {
      "button": "back"
    }
  },
  "settings": {
    "function": "press_button",
    "inputs": {
      "button": "settings"
    }
  },
  "sources": {
    "function": "press_button",
    "inputs": {
      "button": "sources"`
But this solution doesn't work
I also tried to set EXCLUSIVE_MODE = False
The mentioned buttons then work, but the voice, netflix, alexa, etc. buttons do not.
I will be glad for any help, thanks

**Comment by andrewfraley** [comment]
I don't know if you ever got this working, but in case you didn't and you want to try again, try the latest version of the script.  It sleeps for 2s at startup now as I noticed there was frequently an issue at first boot where it wouldn't start.  The logging is also greatly improved so you may gain more insight into where it's getting hung up.

**Comment by Majkysek** [comment]
I will definitely try the new script, and I am glad that it is still being developed. However, I apologize, but my problem was solved a long time ago, I don't know why I didn't mention it here. It was because I used a USB wireless mouse for one trial day. Then I went on vacation and forgot about it when I returned. Then, after about a week, I noticed that I had a USB dongle in my TV. And that was the whole problem—after disconnecting it, everything worked and has been working flawlessly ever since.
