### ISSUE TITLE
Cannot launch app

### ISSUE THREAD

**Issue by kahkhang** [andrewfraley/magic_mapper#2]
Hi, great project!

I have trouble launching an app though, seems like the `launch_app` function in the python script has been removed?

```
Unknown button pressed. (code=412)
Unknown button pressed. (code=28)
netflix button down
netflix button up
firing event for code: 1037
button_name: netflix
func_name: launch_app
Traceback (most recent call last):
  File "/home/root/magic_mapper.py", line 350, in <module>
    main()
  File "/home/root/magic_mapper.py", line 346, in main
    input_loop(button_map=button_map)
  File "/home/root/magic_mapper.py", line 332, in input_loop
    fire_event(code, button_map)
  File "/home/root/magic_mapper.py", line 212, in fire_event
    globals()[func_name](inputs)
KeyError: u'launch_app'
```

**Comment by andrewfraley** [comment]
Thank you, the launch_app function has been restored.
